FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Merge-API

Merge-API is a simple API for processing and managing user data for the Merge Frontend Clients.

Merge is versioned per Semantic Versioning (http://semver.org/)

The current API version is `v0.0.1` and is found at `root/v0/`

The publication of this document marks `v0.0.1`. All API requests will be prefaced with the version number. All requests will accept and return `application/json` format. 


## Trips Collection [/trip]

### Create a Trip [POST]

+ Response 200 (application/json)

## Matches Collection [/match]

### Create a Match [POST]

+ Response 200 (application/json)


## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
