FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Merge-API

Merge-API is a simple API for processing and managing user data for the Merge App Frontend Clients. (http://mergeapp.io)

Merge is versioned per Semantic Versioning (http://semver.org/)

The current API version is `v0.0.1` and is found at `root/v0/`

The publication of this document marks `v0.0.1`. All API requests will be prefaced with the major version number. All requests will accept and return `application/json` format. 


## TripPlanning: [/tripplanning]
### create_trip(user_id, is_driver): [POST]
+ Response 200 (application/json)

### reject_trip(user_id, trip_id): [POST]
+ Response 200 (application/json)

### get_trips(user_id, date_range, is_driver): [GET]
+ Response 200 (application/json)

### get_rejections(user_id): [GET]
+ Response 200 (application/json)

## Matching [/matching]
Responsible for pairing trips

### form_matches(user_id): [POST]
+ Response 200 (application/json)

### get_matches(user_id): [GET]
+ Response 200 (application/json)

### cancel_match(user_id, match_id): [POST]
+ Response 200 (application/json)

### get_cancellations(user_id): [GET]
+ Response 200 (application/json)

## Invitations: [/inviting]

### send_invite(user_id): [POST]
+ Response 200 (application/json)

### get_invite_status(user_id): [GET]
+ Response 200 (application/json)

## UserManager: [/usermanaging]
### get_users(admin_key): [GET]
+ Response 200 (application/json)

### is_admin(user_id): [GET]
+ Response 200 (application/json)

### get_photo(user_id): [GET]
+ Response 200 (application/json)

### set_photo(user_id, photo_uri): [POST]
+ Response 200 (application/json)

### get_licenses(user_id, is_valid): [GET]
+ Response 200 (application/json)

### add_license(user_id): [POST]
+ Response 200 (application/json)

### get_vehicles(user_id): [GET]
+ Response 200 (application/json)

### add_vehicle(user_id): [POST]
+ Response 200 (application/json)

### remove_vehicle(user_id): [POST]
+ Response 200 (application/json)

### get_social_networks(user_id): [GET]
+ Response 200 (application/json)

### set_social_network(user_id, network, network_id): [POST]
+ Response 200 (application/json)

## Scoring: [/scoring]
### get_total_score(user_id): [GET]
+ Response 200 (application/json)

### get_punctionality_score(user_id): [GET]
+ Response 200 (application/json)

### get_friendliness_score(user_id): [GET]
+ Response 200 (application/json)

### set_total_score(user_id): [POST]
+ Response 200 (application/json)

### set_punctionality_score(user_id): [POST]
+ Response 200 (application/json)

### set_friendliness_score(user_id): [POST]
+ Response 200 (application/json)

### get_streak(user_id): [GET]
+ Response 200 (application/json)

### set_streak(user_id, streak_value): [POST]
+ Response 200 (application/json)

### set_multiplier(group_id?, multiplier_value): [POST]
+ Response 200 (application/json)

### get_score_history(user_id, date_range_start, date_range_end): [GET]
+ Response 200 (application/json)

## Registration: [/registering]
### create_user(): [POST]
+ Response 200 (application/json)

## Authentication: [/authenticating]
### get_password_hash(user_id): [GET]
+ Response 200 (application/json)

### set_password_hash(user_id): [POST]
+ Response 200 (application/json)

### login(user_id, token): [POST]
+ Response 200 (application/json)
